In [3]:
# https://towardsdatascience.com/time-series-in-python-exponential-smoothing-and-arima-processes-2c67f2a52788

In [1]:
import requests
import pandas as pd
import json
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
%matplotlib inline
plt.style.use('Solarize_Light2')

r = requests.get('https://datamarket.com/api/v1/list.json?ds=22qx')

print(r)
# jobj = json.loads(r.text[18:-1])
# data = jobj[0]['data']
# df = pd.DataFrame(data, columns['time','data']).set_index('time')
# train = df.iloc[:-10, :]
# test = df.iloc[-10:, :]
# pred = test.copy()


SSLError: HTTPSConnectionPool(host='datamarket.com', port=443): Max retries exceeded with url: /api/v1/list.json?ds=22qx (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),))

In [2]:
# https://blog.goodaudience.com/introduction-to-1d-convolutional-neural-networks-in-keras-for-time-sequences-3a7ff801a2cf
# introduction-to-1d-convolutional-neural-networks LSTM
# https://machinelearningmastery.com/how-to-develop-convolutional-neural-network-models-for-time-series-forecasting/ ** 1 **

In [9]:
import numpy as np
n_steps = 3
n_features = 2
x_input = np.array([[80,85],[90,95],[100,105]])
x_input = x_input.reshape((1, n_steps, n_features))
x_input

array([[[ 80,  85],
        [ 90,  95],
        [100, 105]]])

 !python time_series.py


In [19]:
!python time_series_multiplevariate.py

(7, 3, 2) (7,)
[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [12]:
n_steps = 3
n_features = 1
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1,n_steps, n_features))
x_input

array([[[70],
        [80],
        [90]]])